// Code generated by protoc-gen-go.
// source: heartbeat.proto
// DO NOT EDIT!

/*
Package masterslave is a generated protocol buffer package.

It is generated from these files:
	heartbeat.proto
	masterslave.proto

It has these top-level messages:
	SlaveHeartbeat
	ApplicationStatus
	SlaveCommander
	AddApplicationRequest
	AddApplicationResponse
	StartApplicationsRequest
	StartApplicationsResponse
	StopApplicationRequest
	StopApplicationResponse
	RestartApplicationRequest
	RestartApplicationResponse
	GetApplicationsRequest
	GetApplicationsResponse
	ListApplicationsRequest
	ListApplicationsResponse
	RemoveApplicationsRequest
	RemoveApplicationsResponse
	DeadApplicationRequest
	AddSlaveRequest
	RemoveSlaveRequest
	AddCommanderRequest
	RemoveCommanderRequest
	GetHardwareRequest
	GetHardwareResponse
	GetFileContentRequest
	GetFileContentResponse
	GetFileChecksumRequest
	GetFileChecksumResponse
	RunCommandRequest
	RunCommandResponse
	RunScriptRequest
*/
package masterslave

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SlaveHeartbeat struct {
	SlaveName  *string `protobuf:"bytes,1,req,name=slave_name" json:"slave_name,omitempty"`
	SendTimeUs *int64  `protobuf:"varint,2,req,name=send_time_us" json:"send_time_us,omitempty"`
	// static data
	HostName     *string  `protobuf:"bytes,20,opt,name=host_name" json:"host_name,omitempty"`
	ListenPort   *int32   `protobuf:"varint,21,opt,name=listen_port" json:"listen_port,omitempty"`
	SlavePid     *int32   `protobuf:"varint,22,opt,name=slave_pid" json:"slave_pid,omitempty"`
	StartTimeUs  *int64   `protobuf:"varint,23,opt,name=start_time_us" json:"start_time_us,omitempty"`
	SlaveVersion *string  `protobuf:"bytes,24,opt,name=slave_version" json:"slave_version,omitempty"`
	EnvVars      []string `protobuf:"bytes,25,rep,name=env_vars" json:"env_vars,omitempty"`
	// static proc files per hour
	Cpuinfo *string               `protobuf:"bytes,30,opt,name=cpuinfo" json:"cpuinfo,omitempty"`
	Version *string               `protobuf:"bytes,31,opt,name=version" json:"version,omitempty"`
	EtcMtab *string               `protobuf:"bytes,32,opt,name=etc_mtab" json:"etc_mtab,omitempty"`
	Sysctl  *string               `protobuf:"bytes,33,opt,name=sysctl" json:"sysctl,omitempty"`
	Uname   *SlaveHeartbeat_Uname `protobuf:"bytes,34,opt,name=uname" json:"uname,omitempty"`
	// dynamic proc files 10s
	Meminfo          *string `protobuf:"bytes,40,opt,name=meminfo" json:"meminfo,omitempty"`
	ProcStat         *string `protobuf:"bytes,41,opt,name=proc_stat" json:"proc_stat,omitempty"`
	Loadavg          *string `protobuf:"bytes,42,opt,name=loadavg" json:"loadavg,omitempty"`
	Diskstats        *string `protobuf:"bytes,43,opt,name=diskstats" json:"diskstats,omitempty"`
	NetDev           *string `protobuf:"bytes,44,opt,name=net_dev" json:"net_dev,omitempty"`
	NetTcp           *string `protobuf:"bytes,45,opt,name=net_tcp" json:"net_tcp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SlaveHeartbeat) Reset()                    { *m = SlaveHeartbeat{} }
func (m *SlaveHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*SlaveHeartbeat) ProtoMessage()               {}
func (*SlaveHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SlaveHeartbeat) GetSlaveName() string {
	if m != nil && m.SlaveName != nil {
		return *m.SlaveName
	}
	return ""
}

func (m *SlaveHeartbeat) GetSendTimeUs() int64 {
	if m != nil && m.SendTimeUs != nil {
		return *m.SendTimeUs
	}
	return 0
}

func (m *SlaveHeartbeat) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *SlaveHeartbeat) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *SlaveHeartbeat) GetSlavePid() int32 {
	if m != nil && m.SlavePid != nil {
		return *m.SlavePid
	}
	return 0
}

func (m *SlaveHeartbeat) GetStartTimeUs() int64 {
	if m != nil && m.StartTimeUs != nil {
		return *m.StartTimeUs
	}
	return 0
}

func (m *SlaveHeartbeat) GetSlaveVersion() string {
	if m != nil && m.SlaveVersion != nil {
		return *m.SlaveVersion
	}
	return ""
}

func (m *SlaveHeartbeat) GetEnvVars() []string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *SlaveHeartbeat) GetCpuinfo() string {
	if m != nil && m.Cpuinfo != nil {
		return *m.Cpuinfo
	}
	return ""
}

func (m *SlaveHeartbeat) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *SlaveHeartbeat) GetEtcMtab() string {
	if m != nil && m.EtcMtab != nil {
		return *m.EtcMtab
	}
	return ""
}

func (m *SlaveHeartbeat) GetSysctl() string {
	if m != nil && m.Sysctl != nil {
		return *m.Sysctl
	}
	return ""
}

func (m *SlaveHeartbeat) GetUname() *SlaveHeartbeat_Uname {
	if m != nil {
		return m.Uname
	}
	return nil
}

func (m *SlaveHeartbeat) GetMeminfo() string {
	if m != nil && m.Meminfo != nil {
		return *m.Meminfo
	}
	return ""
}

func (m *SlaveHeartbeat) GetProcStat() string {
	if m != nil && m.ProcStat != nil {
		return *m.ProcStat
	}
	return ""
}

func (m *SlaveHeartbeat) GetLoadavg() string {
	if m != nil && m.Loadavg != nil {
		return *m.Loadavg
	}
	return ""
}

func (m *SlaveHeartbeat) GetDiskstats() string {
	if m != nil && m.Diskstats != nil {
		return *m.Diskstats
	}
	return ""
}

func (m *SlaveHeartbeat) GetNetDev() string {
	if m != nil && m.NetDev != nil {
		return *m.NetDev
	}
	return ""
}

func (m *SlaveHeartbeat) GetNetTcp() string {
	if m != nil && m.NetTcp != nil {
		return *m.NetTcp
	}
	return ""
}

type SlaveHeartbeat_Uname struct {
	Sysname          *string `protobuf:"bytes,1,req,name=sysname" json:"sysname,omitempty"`
	Nodename         *string `protobuf:"bytes,2,req,name=nodename" json:"nodename,omitempty"`
	Release          *string `protobuf:"bytes,3,req,name=release" json:"release,omitempty"`
	Version          *string `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	Machine          *string `protobuf:"bytes,5,req,name=machine" json:"machine,omitempty"`
	Domainname       *string `protobuf:"bytes,6,req,name=domainname" json:"domainname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SlaveHeartbeat_Uname) Reset()                    { *m = SlaveHeartbeat_Uname{} }
func (m *SlaveHeartbeat_Uname) String() string            { return proto.CompactTextString(m) }
func (*SlaveHeartbeat_Uname) ProtoMessage()               {}
func (*SlaveHeartbeat_Uname) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *SlaveHeartbeat_Uname) GetSysname() string {
	if m != nil && m.Sysname != nil {
		return *m.Sysname
	}
	return ""
}

func (m *SlaveHeartbeat_Uname) GetNodename() string {
	if m != nil && m.Nodename != nil {
		return *m.Nodename
	}
	return ""
}

func (m *SlaveHeartbeat_Uname) GetRelease() string {
	if m != nil && m.Release != nil {
		return *m.Release
	}
	return ""
}

func (m *SlaveHeartbeat_Uname) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *SlaveHeartbeat_Uname) GetMachine() string {
	if m != nil && m.Machine != nil {
		return *m.Machine
	}
	return ""
}

func (m *SlaveHeartbeat_Uname) GetDomainname() string {
	if m != nil && m.Domainname != nil {
		return *m.Domainname
	}
	return ""
}

func init() {
	proto.RegisterType((*SlaveHeartbeat)(nil), "masterslave.SlaveHeartbeat")
	proto.RegisterType((*SlaveHeartbeat_Uname)(nil), "masterslave.SlaveHeartbeat.Uname")
}

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x92, 0xcd, 0x52, 0xea, 0x30,
	0x14, 0xc7, 0x07, 0x4a, 0xb9, 0x97, 0x70, 0x81, 0x6b, 0x05, 0x3d, 0xba, 0xd0, 0xc2, 0x0a, 0xbf,
	0x3a, 0x8e, 0x8f, 0xe0, 0xca, 0xbd, 0xe3, 0xc6, 0x4d, 0x26, 0xb4, 0x47, 0xc9, 0xd8, 0x24, 0xb5,
	0x09, 0x9d, 0xf1, 0x0d, 0x7c, 0x6c, 0x4f, 0xc3, 0x84, 0xa9, 0x3b, 0xf2, 0xe3, 0x97, 0xff, 0xf9,
	0x48, 0xd9, 0x6c, 0x8b, 0xa2, 0x76, 0x1b, 0x14, 0x2e, 0xab, 0x6a, 0xe3, 0x4c, 0x32, 0x56, 0xc2,
	0x3a, 0xac, 0x6d, 0x29, 0x1a, 0x5c, 0x7d, 0x0f, 0xd8, 0xf4, 0xb9, 0xfd, 0xf5, 0x14, 0xac, 0x24,
	0x61, 0xcc, 0xff, 0xc7, 0xb5, 0x50, 0x08, 0xbd, 0xb4, 0xbf, 0x1e, 0x25, 0x73, 0xf6, 0xcf, 0xa2,
	0x2e, 0xb8, 0x93, 0x0a, 0xf9, 0xce, 0x42, 0x9f, 0x68, 0x94, 0x1c, 0xb1, 0xd1, 0xd6, 0x58, 0xb7,
	0x17, 0xe7, 0x69, 0x8f, 0xc4, 0x63, 0x36, 0x2e, 0x25, 0xc5, 0x6b, 0x5e, 0x99, 0xda, 0xc1, 0x82,
	0x60, 0xdc, 0x7a, 0xfb, 0xc4, 0x4a, 0x16, 0x70, 0xe2, 0xd1, 0x82, 0x4d, 0xac, 0xa3, 0x8a, 0x87,
	0xc4, 0x53, 0xc2, 0x91, 0xc7, 0xde, 0x6c, 0xa8, 0x41, 0x69, 0x34, 0x80, 0x4f, 0xfd, 0xcf, 0xfe,
	0xa2, 0x6e, 0x78, 0x23, 0x6a, 0x0b, 0x67, 0x69, 0x44, 0x64, 0xc6, 0xfe, 0xe4, 0xd5, 0x4e, 0xea,
	0x37, 0x03, 0x17, 0x5e, 0x21, 0x10, 0xee, 0x5c, 0x1e, 0xee, 0xb8, 0x9c, 0x2b, 0x27, 0x36, 0x90,
	0x7a, 0x32, 0x65, 0x43, 0xfb, 0x65, 0x73, 0x57, 0xc2, 0xd2, 0x9f, 0xef, 0x59, 0xbc, 0xf3, 0xad,
	0xaf, 0xe8, 0x38, 0x7e, 0x58, 0x66, 0x9d, 0xc5, 0x64, 0xbf, 0x97, 0x92, 0xbd, 0xb4, 0x62, 0x5b,
	0x44, 0xa1, 0xf2, 0x55, 0xd7, 0x3e, 0x82, 0x26, 0xa3, 0xa5, 0xe6, 0x9c, 0x66, 0x71, 0x70, 0x15,
	0x1a, 0x29, 0x8d, 0x28, 0x44, 0xf3, 0x0e, 0xd7, 0xc1, 0x29, 0xa4, 0xfd, 0x68, 0x15, 0x0b, 0x37,
	0xc1, 0xd1, 0xe8, 0x78, 0x81, 0x0d, 0xdc, 0x76, 0x81, 0xcb, 0x2b, 0xb8, 0x6b, 0xc1, 0xf9, 0x27,
	0x8b, 0x0f, 0x25, 0xa9, 0xe9, 0xce, 0x53, 0xd0, 0x5c, 0xda, 0x14, 0xe8, 0x49, 0xdf, 0x13, 0x52,
	0x6a, 0x2c, 0x51, 0x58, 0x84, 0x28, 0x80, 0xb0, 0x8b, 0x41, 0x00, 0x4a, 0xe4, 0x5b, 0xa9, 0x11,
	0x62, 0x0f, 0xe8, 0x8d, 0x0b, 0xa3, 0x84, 0xd4, 0x3e, 0x66, 0xd8, 0xb2, 0xc7, 0xc9, 0x6b, 0xf7,
	0xcb, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x57, 0x68, 0xdd, 0x6a, 0x38, 0x02, 0x00, 0x00,
}
