// Code generated by protoc-gen-go.
// source: masterslave.proto
// DO NOT EDIT!

/*
Package masterslave is a generated protocol buffer package.

It is generated from these files:
	masterslave.proto

It has these top-level messages:
	ApplicationStatus
	SlaveCommander
	AddApplicationRequest
	AddApplicationResponse
	StartApplicationsRequest
	StartApplicationsResponse
	StopApplicationRequest
	StopApplicationResponse
	RestartApplicationRequest
	RestartApplicationResponse
	GetApplicationsRequest
	GetApplicationsResponse
	ListApplicationsRequest
	ListApplicationsResponse
	RemoveApplicationsRequest
	RemoveApplicationsResponse
	DeadApplicationRequest
	AddSlaveRequest
	RemoveSlaveRequest
	AddCommanderRequest
	RemoveCommanderRequest
*/
package masterslave

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// application
type ApplicationState int32

const (
	ApplicationState_kUnknown    ApplicationState = 0
	ApplicationState_kNewApp     ApplicationState = 1
	ApplicationState_kRunning    ApplicationState = 2
	ApplicationState_kStopping   ApplicationState = 3
	ApplicationState_kRestarting ApplicationState = 4
	ApplicationState_kExited     ApplicationState = 5
	ApplicationState_kError      ApplicationState = 6
)

var ApplicationState_name = map[int32]string{
	0: "kUnknown",
	1: "kNewApp",
	2: "kRunning",
	3: "kStopping",
	4: "kRestarting",
	5: "kExited",
	6: "kError",
}
var ApplicationState_value = map[string]int32{
	"kUnknown":    0,
	"kNewApp":     1,
	"kRunning":    2,
	"kStopping":   3,
	"kRestarting": 4,
	"kExited":     5,
	"kError":      6,
}

func (x ApplicationState) Enum() *ApplicationState {
	p := new(ApplicationState)
	*p = x
	return p
}
func (x ApplicationState) String() string {
	return proto.EnumName(ApplicationState_name, int32(x))
}
func (x *ApplicationState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApplicationState_value, data, "ApplicationState")
	if err != nil {
		return err
	}
	*x = ApplicationState(value)
	return nil
}
func (ApplicationState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ApplicationStatus struct {
	State            *ApplicationState `protobuf:"varint,1,req,name=state,enum=masterslave.ApplicationState,def=0" json:"state,omitempty"`
	Name             *string           `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Pid              *int32            `protobuf:"varint,3,opt,name=pid" json:"pid,omitempty"`
	ExecutableFile   *string           `protobuf:"bytes,4,opt,name=executable_file" json:"executable_file,omitempty"`
	Cwd              *string           `protobuf:"bytes,5,opt,name=cwd" json:"cwd,omitempty"`
	Message          *string           `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	SlaveName        *string           `protobuf:"bytes,8,opt,name=slave_name" json:"slave_name,omitempty"`
	StartTimeUs      *int64            `protobuf:"varint,10,opt,name=start_time_us" json:"start_time_us,omitempty"`
	LastStopTimeUs   *int64            `protobuf:"varint,11,opt,name=last_stop_time_us" json:"last_stop_time_us,omitempty"`
	ProcStat         *string           `protobuf:"bytes,12,opt,name=proc_stat" json:"proc_stat,omitempty"`
	ProcStatus       *string           `protobuf:"bytes,13,opt,name=proc_status" json:"proc_status,omitempty"`
	LastExitStatus   *int32            `protobuf:"varint,30,opt,name=last_exit_status" json:"last_exit_status,omitempty"`
	LastSignaled     *int32            `protobuf:"varint,31,opt,name=last_signaled" json:"last_signaled,omitempty"`
	LastCoredump     *bool             `protobuf:"varint,32,opt,name=last_coredump" json:"last_coredump,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ApplicationStatus) Reset()                    { *m = ApplicationStatus{} }
func (m *ApplicationStatus) String() string            { return proto.CompactTextString(m) }
func (*ApplicationStatus) ProtoMessage()               {}
func (*ApplicationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ApplicationStatus_State ApplicationState = ApplicationState_kUnknown

func (m *ApplicationStatus) GetState() ApplicationState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_ApplicationStatus_State
}

func (m *ApplicationStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApplicationStatus) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *ApplicationStatus) GetExecutableFile() string {
	if m != nil && m.ExecutableFile != nil {
		return *m.ExecutableFile
	}
	return ""
}

func (m *ApplicationStatus) GetCwd() string {
	if m != nil && m.Cwd != nil {
		return *m.Cwd
	}
	return ""
}

func (m *ApplicationStatus) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ApplicationStatus) GetSlaveName() string {
	if m != nil && m.SlaveName != nil {
		return *m.SlaveName
	}
	return ""
}

func (m *ApplicationStatus) GetStartTimeUs() int64 {
	if m != nil && m.StartTimeUs != nil {
		return *m.StartTimeUs
	}
	return 0
}

func (m *ApplicationStatus) GetLastStopTimeUs() int64 {
	if m != nil && m.LastStopTimeUs != nil {
		return *m.LastStopTimeUs
	}
	return 0
}

func (m *ApplicationStatus) GetProcStat() string {
	if m != nil && m.ProcStat != nil {
		return *m.ProcStat
	}
	return ""
}

func (m *ApplicationStatus) GetProcStatus() string {
	if m != nil && m.ProcStatus != nil {
		return *m.ProcStatus
	}
	return ""
}

func (m *ApplicationStatus) GetLastExitStatus() int32 {
	if m != nil && m.LastExitStatus != nil {
		return *m.LastExitStatus
	}
	return 0
}

func (m *ApplicationStatus) GetLastSignaled() int32 {
	if m != nil && m.LastSignaled != nil {
		return *m.LastSignaled
	}
	return 0
}

func (m *ApplicationStatus) GetLastCoredump() bool {
	if m != nil && m.LastCoredump != nil {
		return *m.LastCoredump
	}
	return false
}

type SlaveCommander struct {
	SlaveName        *string `protobuf:"bytes,1,req,name=slave_name" json:"slave_name,omitempty"`
	CommanderName    *string `protobuf:"bytes,2,opt,name=commander_name" json:"commander_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SlaveCommander) Reset()                    { *m = SlaveCommander{} }
func (m *SlaveCommander) String() string            { return proto.CompactTextString(m) }
func (*SlaveCommander) ProtoMessage()               {}
func (*SlaveCommander) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SlaveCommander) GetSlaveName() string {
	if m != nil && m.SlaveName != nil {
		return *m.SlaveName
	}
	return ""
}

func (m *SlaveCommander) GetCommanderName() string {
	if m != nil && m.CommanderName != nil {
		return *m.CommanderName
	}
	return ""
}

type AddApplicationRequest struct {
	Name             *string         `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Binary           *string         `protobuf:"bytes,2,opt,name=binary" json:"binary,omitempty"`
	Args             []string        `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Envs             []string        `protobuf:"bytes,4,rep,name=envs" json:"envs,omitempty"`
	EnvsOnly         *bool           `protobuf:"varint,5,opt,name=envs_only,def=0" json:"envs_only,omitempty"`
	RedirectStdout   *bool           `protobuf:"varint,6,opt,name=redirect_stdout,def=1" json:"redirect_stdout,omitempty"`
	RedirectStderr   *bool           `protobuf:"varint,7,opt,name=redirect_stderr,def=1" json:"redirect_stderr,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,8,req,name=slave_commander" json:"slave_commander,omitempty"`
	MaxMemoryMb      *int32          `protobuf:"varint,9,opt,name=max_memory_mb,def=32768" json:"max_memory_mb,omitempty"`
	Comment          *string         `protobuf:"bytes,10,opt,name=comment" json:"comment,omitempty"`
	Md5SumFiles      []string        `protobuf:"bytes,20,rep,name=md5sum_files" json:"md5sum_files,omitempty"`
	ExpectedMd5Sums  []string        `protobuf:"bytes,21,rep,name=expected_md5sums" json:"expected_md5sums,omitempty"`
	Md5SumNow        *bool           `protobuf:"varint,22,opt,name=md5sum_now" json:"md5sum_now,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *AddApplicationRequest) Reset()                    { *m = AddApplicationRequest{} }
func (m *AddApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*AddApplicationRequest) ProtoMessage()               {}
func (*AddApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_AddApplicationRequest_EnvsOnly bool = false
const Default_AddApplicationRequest_RedirectStdout bool = true
const Default_AddApplicationRequest_RedirectStderr bool = true
const Default_AddApplicationRequest_MaxMemoryMb int32 = 32768

func (m *AddApplicationRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AddApplicationRequest) GetBinary() string {
	if m != nil && m.Binary != nil {
		return *m.Binary
	}
	return ""
}

func (m *AddApplicationRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AddApplicationRequest) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *AddApplicationRequest) GetEnvsOnly() bool {
	if m != nil && m.EnvsOnly != nil {
		return *m.EnvsOnly
	}
	return Default_AddApplicationRequest_EnvsOnly
}

func (m *AddApplicationRequest) GetRedirectStdout() bool {
	if m != nil && m.RedirectStdout != nil {
		return *m.RedirectStdout
	}
	return Default_AddApplicationRequest_RedirectStdout
}

func (m *AddApplicationRequest) GetRedirectStderr() bool {
	if m != nil && m.RedirectStderr != nil {
		return *m.RedirectStderr
	}
	return Default_AddApplicationRequest_RedirectStderr
}

func (m *AddApplicationRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

func (m *AddApplicationRequest) GetMaxMemoryMb() int32 {
	if m != nil && m.MaxMemoryMb != nil {
		return *m.MaxMemoryMb
	}
	return Default_AddApplicationRequest_MaxMemoryMb
}

func (m *AddApplicationRequest) GetComment() string {
	if m != nil && m.Comment != nil {
		return *m.Comment
	}
	return ""
}

func (m *AddApplicationRequest) GetMd5SumFiles() []string {
	if m != nil {
		return m.Md5SumFiles
	}
	return nil
}

func (m *AddApplicationRequest) GetExpectedMd5Sums() []string {
	if m != nil {
		return m.ExpectedMd5Sums
	}
	return nil
}

func (m *AddApplicationRequest) GetMd5SumNow() bool {
	if m != nil && m.Md5SumNow != nil {
		return *m.Md5SumNow
	}
	return false
}

type AddApplicationResponse struct {
	Status           *ApplicationStatus     `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	PrevRequest      *AddApplicationRequest `protobuf:"bytes,2,opt,name=prev_request" json:"prev_request,omitempty"`
	Md5Sums          []string               `protobuf:"bytes,3,rep,name=md5sums" json:"md5sums,omitempty"`
	SlaveCommander   *SlaveCommander        `protobuf:"bytes,4,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *AddApplicationResponse) Reset()                    { *m = AddApplicationResponse{} }
func (m *AddApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*AddApplicationResponse) ProtoMessage()               {}
func (*AddApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddApplicationResponse) GetStatus() *ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AddApplicationResponse) GetPrevRequest() *AddApplicationRequest {
	if m != nil {
		return m.PrevRequest
	}
	return nil
}

func (m *AddApplicationResponse) GetMd5Sums() []string {
	if m != nil {
		return m.Md5Sums
	}
	return nil
}

func (m *AddApplicationResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type StartApplicationsRequest struct {
	Names            []string        `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *StartApplicationsRequest) Reset()                    { *m = StartApplicationsRequest{} }
func (m *StartApplicationsRequest) String() string            { return proto.CompactTextString(m) }
func (*StartApplicationsRequest) ProtoMessage()               {}
func (*StartApplicationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartApplicationsRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *StartApplicationsRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type StartApplicationsResponse struct {
	Status           []*ApplicationStatus `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	SlaveCommander   *SlaveCommander      `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *StartApplicationsResponse) Reset()                    { *m = StartApplicationsResponse{} }
func (m *StartApplicationsResponse) String() string            { return proto.CompactTextString(m) }
func (*StartApplicationsResponse) ProtoMessage()               {}
func (*StartApplicationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StartApplicationsResponse) GetStatus() []*ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StartApplicationsResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type StopApplicationRequest struct {
	Name             *string         `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *StopApplicationRequest) Reset()                    { *m = StopApplicationRequest{} }
func (m *StopApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*StopApplicationRequest) ProtoMessage()               {}
func (*StopApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StopApplicationRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StopApplicationRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type StopApplicationResponse struct {
	Status           *ApplicationStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	SlaveCommander   *SlaveCommander    `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *StopApplicationResponse) Reset()                    { *m = StopApplicationResponse{} }
func (m *StopApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*StopApplicationResponse) ProtoMessage()               {}
func (*StopApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StopApplicationResponse) GetStatus() *ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StopApplicationResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type RestartApplicationRequest struct {
	Name             *string         `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RestartApplicationRequest) Reset()                    { *m = RestartApplicationRequest{} }
func (m *RestartApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*RestartApplicationRequest) ProtoMessage()               {}
func (*RestartApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RestartApplicationRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RestartApplicationRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type RestartApplicationResponse struct {
	Status           *ApplicationStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	SlaveCommander   *SlaveCommander    `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RestartApplicationResponse) Reset()                    { *m = RestartApplicationResponse{} }
func (m *RestartApplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*RestartApplicationResponse) ProtoMessage()               {}
func (*RestartApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RestartApplicationResponse) GetStatus() *ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RestartApplicationResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type GetApplicationsRequest struct {
	Names            []string        `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetApplicationsRequest) Reset()                    { *m = GetApplicationsRequest{} }
func (m *GetApplicationsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationsRequest) ProtoMessage()               {}
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetApplicationsRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *GetApplicationsRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type GetApplicationsResponse struct {
	Status           []*ApplicationStatus `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	SlaveCommander   *SlaveCommander      `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetApplicationsResponse) Reset()                    { *m = GetApplicationsResponse{} }
func (m *GetApplicationsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationsResponse) ProtoMessage()               {}
func (*GetApplicationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetApplicationsResponse) GetStatus() []*ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetApplicationsResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type ListApplicationsRequest struct {
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ListApplicationsRequest) Reset()                    { *m = ListApplicationsRequest{} }
func (m *ListApplicationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationsRequest) ProtoMessage()               {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListApplicationsRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type ListApplicationsResponse struct {
	Names            []string        `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ListApplicationsResponse) Reset()                    { *m = ListApplicationsResponse{} }
func (m *ListApplicationsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationsResponse) ProtoMessage()               {}
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListApplicationsResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ListApplicationsResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type RemoveApplicationsRequest struct {
	Names            []string        `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	SlaveCommander   *SlaveCommander `protobuf:"bytes,2,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RemoveApplicationsRequest) Reset()                    { *m = RemoveApplicationsRequest{} }
func (m *RemoveApplicationsRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveApplicationsRequest) ProtoMessage()               {}
func (*RemoveApplicationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RemoveApplicationsRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *RemoveApplicationsRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type RemoveApplicationsResponse struct {
	SlaveCommander   *SlaveCommander `protobuf:"bytes,1,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RemoveApplicationsResponse) Reset()                    { *m = RemoveApplicationsResponse{} }
func (m *RemoveApplicationsResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveApplicationsResponse) ProtoMessage()               {}
func (*RemoveApplicationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RemoveApplicationsResponse) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

type DeadApplicationRequest struct {
	AppName          *string           `protobuf:"bytes,1,req,name=appName" json:"appName,omitempty"`
	ProcessID        *int32            `protobuf:"varint,2,req,name=processID" json:"processID,omitempty"`
	ProcessState     *string           `protobuf:"bytes,3,req,name=processState" json:"processState,omitempty"`
	PrevState        *ApplicationState `protobuf:"varint,4,req,name=prevState,enum=masterslave.ApplicationState" json:"prevState,omitempty"`
	SlaveCommander   *SlaveCommander   `protobuf:"bytes,5,req,name=slave_commander" json:"slave_commander,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeadApplicationRequest) Reset()                    { *m = DeadApplicationRequest{} }
func (m *DeadApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeadApplicationRequest) ProtoMessage()               {}
func (*DeadApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeadApplicationRequest) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *DeadApplicationRequest) GetProcessID() int32 {
	if m != nil && m.ProcessID != nil {
		return *m.ProcessID
	}
	return 0
}

func (m *DeadApplicationRequest) GetProcessState() string {
	if m != nil && m.ProcessState != nil {
		return *m.ProcessState
	}
	return ""
}

func (m *DeadApplicationRequest) GetPrevState() ApplicationState {
	if m != nil && m.PrevState != nil {
		return *m.PrevState
	}
	return ApplicationState_kUnknown
}

func (m *DeadApplicationRequest) GetSlaveCommander() *SlaveCommander {
	if m != nil {
		return m.SlaveCommander
	}
	return nil
}

// master-slave
type AddSlaveRequest struct {
	SlaveName        *string `protobuf:"bytes,1,req,name=slave_name" json:"slave_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddSlaveRequest) Reset()                    { *m = AddSlaveRequest{} }
func (m *AddSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*AddSlaveRequest) ProtoMessage()               {}
func (*AddSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AddSlaveRequest) GetSlaveName() string {
	if m != nil && m.SlaveName != nil {
		return *m.SlaveName
	}
	return ""
}

type RemoveSlaveRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveSlaveRequest) Reset()                    { *m = RemoveSlaveRequest{} }
func (m *RemoveSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveSlaveRequest) ProtoMessage()               {}
func (*RemoveSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

// master-commander
type AddCommanderRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddCommanderRequest) Reset()                    { *m = AddCommanderRequest{} }
func (m *AddCommanderRequest) String() string            { return proto.CompactTextString(m) }
func (*AddCommanderRequest) ProtoMessage()               {}
func (*AddCommanderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type RemoveCommanderRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveCommanderRequest) Reset()                    { *m = RemoveCommanderRequest{} }
func (m *RemoveCommanderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCommanderRequest) ProtoMessage()               {}
func (*RemoveCommanderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func init() {
	proto.RegisterType((*ApplicationStatus)(nil), "masterslave.ApplicationStatus")
	proto.RegisterType((*SlaveCommander)(nil), "masterslave.SlaveCommander")
	proto.RegisterType((*AddApplicationRequest)(nil), "masterslave.AddApplicationRequest")
	proto.RegisterType((*AddApplicationResponse)(nil), "masterslave.AddApplicationResponse")
	proto.RegisterType((*StartApplicationsRequest)(nil), "masterslave.StartApplicationsRequest")
	proto.RegisterType((*StartApplicationsResponse)(nil), "masterslave.StartApplicationsResponse")
	proto.RegisterType((*StopApplicationRequest)(nil), "masterslave.StopApplicationRequest")
	proto.RegisterType((*StopApplicationResponse)(nil), "masterslave.StopApplicationResponse")
	proto.RegisterType((*RestartApplicationRequest)(nil), "masterslave.RestartApplicationRequest")
	proto.RegisterType((*RestartApplicationResponse)(nil), "masterslave.RestartApplicationResponse")
	proto.RegisterType((*GetApplicationsRequest)(nil), "masterslave.GetApplicationsRequest")
	proto.RegisterType((*GetApplicationsResponse)(nil), "masterslave.GetApplicationsResponse")
	proto.RegisterType((*ListApplicationsRequest)(nil), "masterslave.ListApplicationsRequest")
	proto.RegisterType((*ListApplicationsResponse)(nil), "masterslave.ListApplicationsResponse")
	proto.RegisterType((*RemoveApplicationsRequest)(nil), "masterslave.RemoveApplicationsRequest")
	proto.RegisterType((*RemoveApplicationsResponse)(nil), "masterslave.RemoveApplicationsResponse")
	proto.RegisterType((*DeadApplicationRequest)(nil), "masterslave.DeadApplicationRequest")
	proto.RegisterType((*AddSlaveRequest)(nil), "masterslave.AddSlaveRequest")
	proto.RegisterType((*RemoveSlaveRequest)(nil), "masterslave.RemoveSlaveRequest")
	proto.RegisterType((*AddCommanderRequest)(nil), "masterslave.AddCommanderRequest")
	proto.RegisterType((*RemoveCommanderRequest)(nil), "masterslave.RemoveCommanderRequest")
	proto.RegisterEnum("masterslave.ApplicationState", ApplicationState_name, ApplicationState_value)
}

var fileDescriptor0 = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0xc6, 0x4e, 0x9c, 0x26, 0xe3, 0xfc, 0x38, 0x3e, 0x4d, 0xba, 0x05, 0xce, 0xa1, 0x8a, 0x84,
	0x54, 0x71, 0x51, 0xa1, 0x00, 0x87, 0xa3, 0x88, 0x9b, 0x03, 0xad, 0x10, 0x12, 0x2a, 0x52, 0x23,
	0x6e, 0x10, 0xc8, 0xb8, 0xf1, 0x34, 0xb2, 0xe2, 0x3f, 0x76, 0xed, 0x34, 0xbd, 0x42, 0xf0, 0x58,
	0xbc, 0x01, 0xb7, 0xf0, 0x42, 0xcc, 0xae, 0x9d, 0x90, 0x26, 0xee, 0x49, 0x55, 0xb5, 0xbd, 0x8b,
	0x67, 0x66, 0x67, 0xbe, 0xef, 0x9b, 0xd9, 0xcd, 0x40, 0x37, 0x74, 0x45, 0x8a, 0x5c, 0x04, 0xee,
	0x1c, 0x4f, 0x12, 0x1e, 0xa7, 0xb1, 0x6d, 0xae, 0x99, 0x06, 0xff, 0xea, 0xd0, 0x7d, 0x9b, 0x24,
	0x81, 0x3f, 0x71, 0x53, 0x3f, 0x8e, 0xc6, 0xa9, 0x9b, 0x66, 0xc2, 0x7e, 0x0d, 0x86, 0xa0, 0x5f,
	0xc8, 0xb4, 0x23, 0xfd, 0xb8, 0x3d, 0x7c, 0x79, 0xb2, 0x9e, 0x65, 0x23, 0x1c, 0x47, 0xf5, 0xd9,
	0x8f, 0xd1, 0x2c, 0x8a, 0xaf, 0x23, 0xbb, 0x09, 0xd5, 0xc8, 0x0d, 0x91, 0xe9, 0x74, 0xac, 0x61,
	0x9b, 0x50, 0x49, 0x7c, 0x8f, 0x55, 0x8e, 0xb4, 0x63, 0xc3, 0x3e, 0x80, 0x0e, 0x2e, 0x70, 0x92,
	0xa5, 0xee, 0x65, 0x80, 0xce, 0x95, 0x1f, 0x20, 0xab, 0x92, 0x43, 0x45, 0x4d, 0xae, 0x3d, 0x66,
	0xa8, 0x8f, 0x0e, 0xec, 0x85, 0x28, 0x84, 0x3b, 0x45, 0x56, 0x53, 0x06, 0x1b, 0x40, 0x55, 0x75,
	0x54, 0xde, 0xba, 0xb2, 0xf5, 0xa0, 0x45, 0xe8, 0x78, 0xea, 0xa4, 0x7e, 0x88, 0x4e, 0x26, 0x18,
	0x90, 0xb9, 0x62, 0x1f, 0x42, 0x37, 0x20, 0x98, 0x8e, 0x48, 0xe3, 0x64, 0xe5, 0x32, 0x95, 0xab,
	0x0b, 0x0d, 0xe2, 0x3e, 0x71, 0x24, 0x29, 0xd6, 0x54, 0x49, 0x5e, 0x80, 0xb9, 0x32, 0x51, 0x5c,
	0x4b, 0x19, 0x19, 0x58, 0x2a, 0x05, 0x2e, 0xfc, 0x74, 0xe9, 0x79, 0xa5, 0xe0, 0x53, 0xcd, 0x3c,
	0xb9, 0x3f, 0x8d, 0xdc, 0x00, 0x3d, 0xf6, 0xd1, 0x2d, 0xf3, 0x24, 0xe6, 0xe8, 0x65, 0x61, 0xc2,
	0x8e, 0xc8, 0x5c, 0x1f, 0x7c, 0x05, 0xed, 0xb1, 0x44, 0xfd, 0x4d, 0x1c, 0x86, 0x6e, 0xe4, 0x21,
	0xdf, 0xe0, 0xa1, 0x29, 0x7d, 0xfa, 0xd0, 0x9e, 0x2c, 0x03, 0x9c, 0x42, 0x37, 0x42, 0x31, 0xf8,
	0x47, 0x87, 0xde, 0x5b, 0xcf, 0x5b, 0xd3, 0xf9, 0x02, 0x7f, 0xcb, 0x50, 0xa4, 0x2b, 0x7d, 0xf3,
	0xf3, 0x6d, 0xa8, 0x5d, 0xfa, 0x91, 0xcb, 0x6f, 0xf2, 0x73, 0xd2, 0xeb, 0xf2, 0xa9, 0x20, 0xc1,
	0x2b, 0xf9, 0x17, 0x46, 0x73, 0x41, 0x2a, 0x57, 0x14, 0xb3, 0x86, 0xfc, 0x72, 0xe2, 0x28, 0xb8,
	0x51, 0x5a, 0xd7, 0x47, 0xc6, 0x95, 0x1b, 0x08, 0xb4, 0x5f, 0x42, 0x87, 0xb0, 0xfb, 0x1c, 0x27,
	0x92, 0xb2, 0x17, 0x67, 0xa9, 0x92, 0xbe, 0x3e, 0xaa, 0xa6, 0x3c, 0xdb, 0x72, 0x23, 0xe7, 0x6c,
	0x6f, 0xcd, 0xfd, 0x39, 0x74, 0x72, 0x5e, 0x2b, 0x26, 0xd4, 0x24, 0xfd, 0xd8, 0x1c, 0x7e, 0x70,
	0x6b, 0x66, 0x36, 0xd4, 0xf8, 0x10, 0x5a, 0xa1, 0xbb, 0x70, 0x42, 0x0c, 0x63, 0x7e, 0xe3, 0x84,
	0x97, 0xac, 0x21, 0xd5, 0x1c, 0x19, 0x9f, 0x0d, 0xbf, 0x7c, 0xfd, 0x46, 0x0e, 0x81, 0xcc, 0x86,
	0x51, 0xaa, 0x3a, 0xdb, 0xb0, 0xf7, 0xa1, 0x19, 0x7a, 0x5f, 0x88, 0x2c, 0x54, 0x73, 0x23, 0xd8,
	0x7e, 0x41, 0xc9, 0xc2, 0x45, 0x42, 0xb8, 0xd0, 0x73, 0x72, 0xb7, 0x60, 0x3d, 0xe5, 0x21, 0xb1,
	0x8b, 0x78, 0x9a, 0x4a, 0xd6, 0x57, 0x2d, 0xf9, 0x5b, 0x83, 0xfe, 0xa6, 0xa8, 0x22, 0x89, 0x23,
	0x52, 0xe0, 0x04, 0x6a, 0x45, 0xaf, 0x35, 0x0a, 0x35, 0x87, 0xaf, 0xde, 0x35, 0xee, 0x74, 0x3b,
	0xde, 0x40, 0x33, 0xe1, 0x38, 0x77, 0x78, 0xde, 0x15, 0xa5, 0xbe, 0x39, 0x1c, 0xdc, 0x3e, 0x55,
	0xda, 0x3f, 0x39, 0xde, 0x05, 0xd2, 0xbc, 0x49, 0x25, 0xf2, 0x55, 0x77, 0xca, 0x37, 0x70, 0x80,
	0x8d, 0xe5, 0x05, 0x58, 0xab, 0x20, 0x96, 0x25, 0x5a, 0x60, 0xc8, 0x11, 0x91, 0x5c, 0xee, 0x28,
	0xa0, 0xef, 0x2e, 0xf0, 0x87, 0x06, 0x87, 0x25, 0x15, 0x4a, 0xf4, 0xaa, 0xdc, 0x43, 0xaf, 0x87,
	0x61, 0xf8, 0x19, 0xfa, 0x63, 0xba, 0xc9, 0x3b, 0x6f, 0xc1, 0xc3, 0xb2, 0xff, 0x0e, 0x07, 0x5b,
	0xd9, 0x4b, 0xe8, 0xe9, 0x4f, 0x46, 0xcf, 0x81, 0x43, 0xaa, 0xb8, 0xa1, 0xf1, 0x63, 0x32, 0xfc,
	0x53, 0x83, 0xf7, 0xcb, 0x2a, 0x3c, 0x2b, 0xcb, 0x5f, 0xa0, 0xff, 0x2d, 0x3e, 0xdd, 0x9c, 0x52,
	0x17, 0xb7, 0xd2, 0x3f, 0xeb, 0x90, 0xfe, 0x00, 0x07, 0xdf, 0xfb, 0xa2, 0x94, 0xe0, 0x43, 0xc7,
	0x82, 0x6d, 0x27, 0x2c, 0x28, 0x3d, 0x8a, 0x64, 0xbf, 0xca, 0xb9, 0x0b, 0xe3, 0x39, 0x3e, 0x59,
	0x53, 0x2e, 0xe4, 0xdc, 0x6d, 0x57, 0x28, 0x48, 0x94, 0xe4, 0xd4, 0x76, 0xe7, 0xfc, 0x8b, 0x5e,
	0xef, 0x53, 0x74, 0xef, 0x78, 0x53, 0xdd, 0x24, 0x39, 0xff, 0xff, 0xba, 0x14, 0x7f, 0xf6, 0xb4,
	0x46, 0x7c, 0x77, 0xaa, 0xf0, 0x1a, 0xf2, 0x0f, 0xa4, 0x30, 0xa9, 0x8d, 0x85, 0x1e, 0x5f, 0x19,
	0xf8, 0xa9, 0x0c, 0xc4, 0x79, 0x6e, 0xaa, 0xde, 0x63, 0xd3, 0x29, 0x03, 0x6f, 0xec, 0x06, 0xff,
	0x31, 0x74, 0xe8, 0xef, 0x40, 0x19, 0x97, 0xa0, 0x4b, 0xd6, 0x81, 0xc1, 0x3e, 0xd8, 0xb9, 0x6e,
	0xeb, 0x91, 0x83, 0x1e, 0xbc, 0xa0, 0xc3, 0xab, 0x64, 0x4b, 0x33, 0x83, 0x7e, 0x1e, 0xbc, 0xe9,
	0xf9, 0x24, 0x05, 0x6b, 0x0b, 0x77, 0x13, 0x56, 0x3b, 0x9a, 0xf5, 0x1e, 0x6d, 0x5c, 0x7b, 0xb3,
	0x73, 0xbc, 0xa6, 0x28, 0x4b, 0x53, 0xae, 0x8b, 0x2c, 0x8a, 0xfc, 0x68, 0x6a, 0xe9, 0x34, 0x00,
	0x8d, 0x99, 0x7c, 0x17, 0x13, 0xf9, 0x59, 0x21, 0x6d, 0xcd, 0x59, 0xf1, 0x86, 0x48, 0x43, 0x55,
	0x1d, 0x3d, 0xa3, 0xe5, 0x08, 0x3d, 0xcb, 0x20, 0x0e, 0xb5, 0xd9, 0x19, 0xe7, 0x31, 0xb7, 0x6a,
	0x5f, 0xb7, 0x7e, 0x5a, 0x5f, 0x2b, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x68, 0xa0, 0x39, 0x85,
	0x77, 0x0a, 0x00, 0x00,
}
