// Code generated by protoc-gen-go.
// source: logingate.proto
// DO NOT EDIT!

/*
Package userproto is a generated protocol buffer package.

It is generated from these files:
	logingate.proto
	loginlogin.proto

It has these top-level messages:
	UserLoginGateRequest
	UserLoginGateResponse
	UserLoginLoginRequest
	UserLoginLoginResponse
*/
package userproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type UserLoginGateState int32

const (
	UserLoginGateState_kEncryptError     UserLoginGateState = 0
	UserLoginGateState_kNameError        UserLoginGateState = 1
	UserLoginGateState_kLoginGateSuccess UserLoginGateState = 2
)

var UserLoginGateState_name = map[int32]string{
	0: "kEncryptError",
	1: "kNameError",
	2: "kLoginGateSuccess",
}
var UserLoginGateState_value = map[string]int32{
	"kEncryptError":     0,
	"kNameError":        1,
	"kLoginGateSuccess": 2,
}

func (x UserLoginGateState) Enum() *UserLoginGateState {
	p := new(UserLoginGateState)
	*p = x
	return p
}
func (x UserLoginGateState) String() string {
	return proto.EnumName(UserLoginGateState_name, int32(x))
}
func (x *UserLoginGateState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserLoginGateState_value, data, "UserLoginGateState")
	if err != nil {
		return err
	}
	*x = UserLoginGateState(value)
	return nil
}
func (UserLoginGateState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// user->gate
type UserLoginGateRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	EncryptedKey     []byte  `protobuf:"bytes,2,req,name=encryptedKey" json:"encryptedKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginGateRequest) Reset()                    { *m = UserLoginGateRequest{} }
func (m *UserLoginGateRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginGateRequest) ProtoMessage()               {}
func (*UserLoginGateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserLoginGateRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserLoginGateRequest) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

// gate->user
type UserLoginGateResponse struct {
	State            *UserLoginGateState `protobuf:"varint,1,req,name=state,enum=userproto.UserLoginGateState" json:"state,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UserLoginGateResponse) Reset()                    { *m = UserLoginGateResponse{} }
func (m *UserLoginGateResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginGateResponse) ProtoMessage()               {}
func (*UserLoginGateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserLoginGateResponse) GetState() UserLoginGateState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return UserLoginGateState_kEncryptError
}

func init() {
	proto.RegisterType((*UserLoginGateRequest)(nil), "userproto.UserLoginGateRequest")
	proto.RegisterType((*UserLoginGateResponse)(nil), "userproto.UserLoginGateResponse")
	proto.RegisterEnum("userproto.UserLoginGateState", UserLoginGateState_name, UserLoginGateState_value)
}

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0xcf,
	0xcc, 0x4b, 0x4f, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x2d, 0x4e,
	0x2d, 0x02, 0x33, 0x95, 0xac, 0xb8, 0x44, 0x42, 0x81, 0x1c, 0x1f, 0x90, 0x0a, 0x77, 0xa0, 0x8a,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x1e, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09,
	0x46, 0x05, 0x26, 0x0d, 0x4e, 0x21, 0x11, 0x2e, 0x9e, 0xd4, 0xbc, 0xe4, 0xa2, 0xca, 0x82, 0x92,
	0xd4, 0x14, 0xef, 0xd4, 0x4a, 0x09, 0x26, 0xa0, 0x28, 0x8f, 0x92, 0x2b, 0x97, 0x28, 0x9a, 0xde,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x1d, 0x2e, 0xd6, 0xe2, 0x12, 0xa0, 0x00, 0x58, 0x37,
	0x9f, 0x91, 0xac, 0x1e, 0xdc, 0x3e, 0x3d, 0x14, 0x0d, 0xc1, 0x20, 0x45, 0x5a, 0x7e, 0x5c, 0x42,
	0x98, 0xa2, 0x42, 0x82, 0x5c, 0xbc, 0xd9, 0xae, 0x10, 0x3b, 0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x04,
	0x18, 0x84, 0xf8, 0xb8, 0xb8, 0xb2, 0xfd, 0x80, 0x8e, 0x82, 0xf0, 0x19, 0x85, 0x44, 0xb9, 0x04,
	0xb3, 0x11, 0xba, 0x4a, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0x05, 0x98, 0x9c, 0xb8, 0xa3, 0x10, 0xfe,
	0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe8, 0xfe, 0x5e, 0xfc, 0x00, 0x00, 0x00,
}
