// Code generated by protoc-gen-go.
// source: gatelogin.proto
// DO NOT EDIT!

/*
Package gatelogin is a generated protocol buffer package.

It is generated from these files:
	gatelogin.proto

It has these top-level messages:
	GateLoginRequest
	UserRandomKeyRequest
*/
package gatelogin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// gate->login
type GateLoginRequest struct {
	Zone              *int32  `protobuf:"varint,1,req,name=zone" json:"zone,omitempty"`
	GateListenAddress *string `protobuf:"bytes,2,req,name=gateListenAddress" json:"gateListenAddress,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *GateLoginRequest) Reset()                    { *m = GateLoginRequest{} }
func (m *GateLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*GateLoginRequest) ProtoMessage()               {}
func (*GateLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GateLoginRequest) GetZone() int32 {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return 0
}

func (m *GateLoginRequest) GetGateListenAddress() string {
	if m != nil && m.GateListenAddress != nil {
		return *m.GateListenAddress
	}
	return ""
}

// login->gate
type UserRandomKeyRequest struct {
	Zone             *int32  `protobuf:"varint,1,req,name=zone" json:"zone,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	RandomKey        []byte  `protobuf:"bytes,3,req,name=randomKey" json:"randomKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserRandomKeyRequest) Reset()                    { *m = UserRandomKeyRequest{} }
func (m *UserRandomKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRandomKeyRequest) ProtoMessage()               {}
func (*UserRandomKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRandomKeyRequest) GetZone() int32 {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return 0
}

func (m *UserRandomKeyRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserRandomKeyRequest) GetRandomKey() []byte {
	if m != nil {
		return m.RandomKey
	}
	return nil
}

func init() {
	proto.RegisterType((*GateLoginRequest)(nil), "gatelogin.GateLoginRequest")
	proto.RegisterType((*UserRandomKeyRequest)(nil), "gatelogin.UserRandomKeyRequest")
}

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4f, 0x2c, 0x49,
	0xcd, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x59, 0x73, 0x09, 0xb8, 0x03, 0x39, 0x3e, 0x20, 0x4e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89,
	0x10, 0x0f, 0x17, 0x4b, 0x55, 0x7e, 0x5e, 0xaa, 0x04, 0xa3, 0x02, 0x93, 0x06, 0xab, 0x90, 0x24,
	0x97, 0x20, 0x48, 0xb9, 0x4f, 0x66, 0x71, 0x49, 0x6a, 0x9e, 0x63, 0x4a, 0x4a, 0x51, 0x6a, 0x71,
	0xb1, 0x04, 0x13, 0x50, 0x8a, 0x53, 0xc9, 0x95, 0x4b, 0x24, 0xb4, 0x38, 0xb5, 0x28, 0x28, 0x31,
	0x2f, 0x25, 0x3f, 0xd7, 0x3b, 0xb5, 0x12, 0xbb, 0x01, 0x40, 0x5e, 0x5e, 0x62, 0x6e, 0x2a, 0x44,
	0x8f, 0x90, 0x20, 0x17, 0x67, 0x11, 0x4c, 0xbd, 0x04, 0x33, 0x50, 0x88, 0xc7, 0x89, 0x3b, 0x0a,
	0xe1, 0x20, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x68, 0x01, 0xa0, 0xad, 0x00, 0x00, 0x00,
}
