// Code generated by protoc-gen-go.
// source: shiranMessage.proto
// DO NOT EDIT!

/*
Package shiran is a generated protocol buffer package.

It is generated from these files:
	shiranMessage.proto

It has these top-level messages:
	ShiranMessage
*/
package shiran

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ShiranMessage struct {
	Service          *string `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	Msg              []byte  `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShiranMessage) Reset()                    { *m = ShiranMessage{} }
func (m *ShiranMessage) String() string            { return proto.CompactTextString(m) }
func (*ShiranMessage) ProtoMessage()               {}
func (*ShiranMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ShiranMessage) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *ShiranMessage) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *ShiranMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ShiranMessage)(nil), "shiran.ShiranMessage")
}

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xce, 0xc8, 0x2c,
	0x4a, 0xcc, 0xf3, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x83, 0x08, 0x2a, 0xd9, 0x72, 0xf1, 0x06, 0x23, 0x4b, 0x0b, 0xf1, 0x73, 0xb1, 0x17, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x0a, 0xf1, 0x71, 0xb1, 0xe5,
	0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x48, 0x30, 0x81, 0xf9, 0xdc, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x12,
	0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x4e, 0x1c, 0x51, 0x50, 0x83, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0x59, 0x61, 0xa0, 0x66, 0x00, 0x00, 0x00,
}
